/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/derive": {
    /**
     * Derive the full state
     * @description Derive everything from one complete curation state.
     *
     * 404 when the pull is gone — a stale workspace pointing at a deleted pull
     * is a normal condition, not a server error. 422 (from the request model)
     * for an unknown field, a `selections` key, or a negative weight: each of
     * those is curation that would otherwise fail silently.
     */
    post: operations["post_derive_api_derive_post"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * Anchor
     * @description The market reference point, with its sensitivity band.
     *
     * NORTH_STAR: never rendered without the band — it depends on a manual
     * assumption (drift), so a point estimate would be a claim the evidence does
     * not support.
     */
    Anchor: {
      rent: components["schemas"]["Band_float_"];
      psf: components["schemas"]["Band_float_"];
      /** Drift Pct */
      drift_pct: number;
      /** Drift Sensitivity Pts */
      drift_sensitivity_pts: number;
      /** Subject Sqft */
      subject_sqft: number;
      /** N Comps */
      n_comps: number;
      /** Comp Keys */
      comp_keys: string[];
    };
    /** Band[KMCurve] */
    Band_KMCurve_: {
      low: components["schemas"]["KMCurve"];
      mid: components["schemas"]["KMCurve"];
      high: components["schemas"]["KMCurve"];
    };
    /** Band[float] */
    Band_float_: {
      /** Low */
      low: number;
      /** Mid */
      mid: number;
      /** High */
      high: number;
    };
    /**
     * Breakdown
     * @description Where every pulled comp went. `included + excluded + filtered == pulled`
     * (F7-S1 [INVARIANT]), computed in one place so the count and the per-comp
     * label can never disagree.
     *
     * `comp_keys` maps each count to the comps behind it — including
     * `missing_sqft`, which is the one evidence-excluded set that still has to
     * be reachable by a click (T-S2).
     */
    Breakdown: {
      /** Pulled */
      pulled: number;
      /** Included */
      included: number;
      /** Excluded */
      excluded: number;
      /** Filtered */
      filtered: number;
      /** Censored */
      censored: number;
      /** Pending */
      pending: number;
      /** Provisional */
      provisional: number;
      /** Missing Sqft */
      missing_sqft: number;
      /** Per Cohort */
      per_cohort: components["schemas"]["CohortCount"][];
      /** Comp Keys */
      comp_keys: {
        [key: string]: string[];
      };
    };
    /**
     * BucketStat
     * @description One premium bucket: a stable % definition, a live dollar translation.
     *
     * NORTH_STAR: buckets never interpolate. An empty bucket carries `None`
     * statistics — the view renders a dash, never an estimate.
     */
    BucketStat: {
      /**
       * Id
       * @enum {string}
       */
      id: "below" | "at" | "above";
      /** Premium Min */
      premium_min: number | null;
      /** Premium Max */
      premium_max: number | null;
      dollar_min: components["schemas"]["Band_float_"] | null;
      dollar_max: components["schemas"]["Band_float_"] | null;
      /** Count */
      count: number;
      /** Leased Dom Median */
      leased_dom_median: number | null;
      /** Leased Dom Min */
      leased_dom_min: number | null;
      /** Leased Dom Max */
      leased_dom_max: number | null;
      /** Cut Before Lease Rate */
      cut_before_lease_rate: number | null;
      /** Provisional Count */
      provisional_count: number;
      /** Withdrawal Suspect Count */
      withdrawal_suspect_count: number;
      /** Censored Floors */
      censored_floors: number[];
      /** Comp Keys */
      comp_keys: string[];
    };
    /** CohortCount */
    CohortCount: {
      /** Year */
      year: number;
      /** Count */
      count: number;
      /** Comp Keys */
      comp_keys: string[];
    };
    /**
     * CohortStat
     * @description One listing-year's median $/sqft, and the evidence behind it.
     */
    CohortStat: {
      /** Year */
      year: number;
      /** Selected Count */
      selected_count: number;
      /** Pulled Count */
      pulled_count: number;
      /** Median Psf */
      median_psf: number | null;
      /** Basis */
      basis: ("selected" | "pulled") | null;
      /** Thin */
      thin: boolean;
      /** Comp Keys */
      comp_keys: string[];
    };
    /**
     * Config
     * @description The §2.3 knobs as an immutable value object.
     *
     * Frozen (no rebinding of any knob) and `extra="forbid"` (an unrecognized
     * keyword is an error, which is also what rejects `query_padding_days` and
     * typo'd knob names coming out of the file).
     */
    Config: {
      /**
       * Stitch Gap Days
       * @default 42
       */
      stitch_gap_days?: number;
      /**
       * Provisional Lease Days
       * @default 7
       */
      provisional_lease_days?: number;
      /**
       * Withdrawal Suspect Months
       * @default 6
       */
      withdrawal_suspect_months?: number;
      /**
       * Knn K
       * @default 7
       */
      knn_k?: number;
      /**
       * Bucket Half Width Pct
       * @default 4
       */
      bucket_half_width_pct?: number;
      /**
       * Min Cohort Size
       * @default 4
       */
      min_cohort_size?: number;
      /**
       * Drift Source
       * @default manual
       * @enum {string}
       */
      drift_source?: "zip" | "cohort" | "manual";
      /**
       * Km Horizons Days
       * @default [
       *   14,
       *   30,
       *   45,
       *   60
       * ]
       */
      km_horizons_days?: number[];
    };
    /**
     * CurveResult
     * @description The price test when the evidence supports a curve.
     */
    CurveResult: {
      /**
       * State
       * @default curve
       * @constant
       */
      state?: "curve";
      /** Candidate Rent */
      candidate_rent: number;
      candidate_premium: components["schemas"]["Band_float_"];
      /**
       * Bucket
       * @enum {string}
       */
      bucket: "below" | "at" | "above";
      /** Neighbors */
      neighbors: components["schemas"]["Neighbor"][];
      curve: components["schemas"]["Band_KMCurve_"];
      /** Horizons */
      horizons: components["schemas"]["HorizonReadout"][];
      expected_vacancy: components["schemas"]["ExpectedVacancy"];
    };
    /**
     * Cut
     * @description One price reduction in a comp's history, on the wire.
     */
    Cut: {
      /**
       * On
       * Format: date
       */
      on: string;
      /** From Price */
      from_price: number;
      /** To Price */
      to_price: number;
    };
    /**
     * DeriveMeta
     * @description Provenance. Deliberately contains no clock reading of any kind.
     */
    DeriveMeta: {
      /**
       * As Of
       * Format: date
       */
      as_of: string;
      /** Pull Ref */
      pull_ref: string;
      /** Pull Digest */
      pull_digest: string;
      /** Config Digest */
      config_digest: string;
      /** Pipeline Version */
      pipeline_version: string;
      config: components["schemas"]["Config"];
      partial_pull?: components["schemas"]["PartialPullInfo"] | null;
    };
    /**
     * DeriveRequest
     * @description The complete curation state — the whole input to one derivation pass.
     *
     * Frozen so no stage can mutate the request and leave a footprint for the
     * next one (ADR-001 §4.3); `extra="forbid"` so a typo'd field is a loud 422
     * rather than curation that silently fails to apply.
     */
    DeriveRequest: {
      /** Pull Ref */
      pull_ref: string;
      subject: components["schemas"]["Subject"];
      /** Weights */
      weights?: {
        [key: string]: number;
      };
      /** Include Overrides */
      include_overrides?: string[];
      filters?: components["schemas"]["Filters"];
      /**
       * Drift Pct
       * @default 0
       */
      drift_pct?: number;
      /** Candidate Rent */
      candidate_rent?: number | null;
    };
    /**
     * DerivedComp
     * @description One comp as the view sees it — evidence plus its derived position.
     *
     * Note what is *not* here: any listing id. F13-S1 [INVARIANT] keys curation
     * by normalized address+unit because ids churn between pulls, and nothing
     * downstream may be tempted to key on something that churns.
     */
    DerivedComp: {
      /** Key */
      key: string;
      /** Address */
      address: string;
      /** Unit */
      unit: string | null;
      /** Lat */
      lat: number;
      /** Lng */
      lng: number;
      /** Beds */
      beds: number;
      /** Baths */
      baths: number | null;
      /** Sqft */
      sqft: number | null;
      /** Initial Ask */
      initial_ask: number;
      /** Psf */
      psf: number | null;
      /** Premium */
      premium: number | null;
      /** Premium Basis */
      premium_basis: ("selected" | "pulled") | null;
      /** Cohort Year */
      cohort_year: number;
      /** Effective Dom */
      effective_dom: number;
      /** Censored */
      censored: boolean;
      /** Removal Class */
      removal_class: ("pending" | "provisional" | "confirmed") | null;
      /** Withdrawal Suspect */
      withdrawal_suspect: boolean;
      /** Sqft Suspect */
      sqft_suspect: boolean;
      /** Cut History */
      cut_history: components["schemas"]["Cut"][];
      /** Relist Count */
      relist_count: number;
      /** Gap Days */
      gap_days: number;
      /** Distance Mi */
      distance_mi: number;
      /** Weight */
      weight: number;
      /** Contribution Share */
      contribution_share: number | null;
      /**
       * State
       * @enum {string}
       */
      state: "included" | "excluded" | "filtered";
      /** Bucket */
      bucket: ("below" | "at" | "above") | null;
    };
    /**
     * DerivedState
     * @description One derivation pass, whole.
     */
    DerivedState: {
      /** Comps */
      comps: components["schemas"]["DerivedComp"][];
      /** Cohorts */
      cohorts: components["schemas"]["CohortStat"][];
      anchor: components["schemas"]["Anchor"] | null;
      /** Buckets */
      buckets: components["schemas"]["BucketStat"][];
      /** Price Test */
      price_test: (components["schemas"]["CurveResult"] | components["schemas"]["GuardResult"]) | null;
      breakdown: components["schemas"]["Breakdown"];
      /** Warnings */
      warnings: components["schemas"]["DerivedWarning"][];
      meta: components["schemas"]["DeriveMeta"];
    };
    /**
     * DerivedWarning
     * @description Something the user must know about this derive.
     *
     * Named `DerivedWarning` rather than ADR-001 §1.2's sketch spelling
     * `Warning` so the module does not shadow the builtin (the field is still
     * `warnings`; the wire shape is unchanged).
     *
     * A warning never carries its own `comp_keys` list. It points at one of
     * `breakdown.comp_keys`' entries instead, so the comps behind a warning and
     * the comps behind the count that produced it are literally the same list —
     * two lists could disagree, and a `comp_keys` list outside `breakdown` reads
     * as an *evidence* list (the comps a statistic was computed from), which is
     * the opposite of what a warning names.
     */
    DerivedWarning: {
      /** Code */
      code: string;
      /** Message */
      message: string;
      /** Breakdown Ref */
      breakdown_ref?: string | null;
    };
    /**
     * ExpectedVacancy
     * @description Area under the truncated KM step function, in days and dollars.
     *
     * Always stated with its truncation point (NORTH_STAR): it is an expected
     * value under a *truncated* empirical curve, not a guarantee and not valid
     * beyond the observation window.
     */
    ExpectedVacancy: {
      days: components["schemas"]["Band_float_"];
      cost: components["schemas"]["Band_float_"];
      /** Truncated At */
      truncated_at: number;
    };
    /**
     * Filters
     * @description The F7-S1 filter set. Filters *re-label* comps, never remove them.
     */
    Filters: {
      /** Max Distance Mi */
      max_distance_mi?: number | null;
      /**
       * Hide Censored
       * @default false
       */
      hide_censored?: boolean;
      /**
       * Leased Only
       * @default false
       */
      leased_only?: boolean;
    };
    /**
     * GuardResult
     * @description The price test when it does not.
     *
     * This is a *different render*, not a curve with wide error bars — the two
     * are mutually exclusive by construction (F11-S3 [INVARIANT], NORTH_STAR).
     * The nearest comps are still surfaced, with their distances, so the user
     * can see exactly how thin the evidence is (spec §5.4).
     */
    GuardResult: {
      /**
       * State
       * @default insufficient_evidence
       * @constant
       */
      state?: "insufficient_evidence";
      /** Candidate Rent */
      candidate_rent: number;
      candidate_premium: components["schemas"]["Band_float_"];
      /**
       * Bucket
       * @enum {string}
       */
      bucket: "below" | "at" | "above";
      /**
       * Reason
       * @enum {string}
       */
      reason: "too_few_in_range" | "all_censored";
      /** Neighbors */
      neighbors: components["schemas"]["Neighbor"][];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HorizonReadout */
    HorizonReadout: {
      /** Day */
      day: number;
      survival: components["schemas"]["Band_float_"];
    };
    /** KMCurve */
    KMCurve: {
      /** Points */
      points: components["schemas"]["KMPoint"][];
      /** Truncated At */
      truncated_at: number | null;
    };
    /**
     * KMPoint
     * @description One step of a Kaplan-Meier product-limit estimate (F11-S2).
     */
    KMPoint: {
      /** Day */
      day: number;
      /** Survival */
      survival: number;
      /** At Risk */
      at_risk: number;
      /** Events */
      events: number;
      /** Censored Count */
      censored_count: number;
    };
    /**
     * Neighbor
     * @description A comp retrieved by the kNN stage, with its distance in premium space.
     */
    Neighbor: {
      /** Key */
      key: string;
      /** Premium */
      premium: number;
      /** Distance */
      distance: number;
      /** Effective Dom */
      effective_dom: number;
      /** Censored */
      censored: boolean;
      /** Removal Class */
      removal_class: ("pending" | "provisional" | "confirmed") | null;
      /** Weight */
      weight: number;
      /** Cohort Year */
      cohort_year: number;
      /** Cut Count */
      cut_count: number;
    };
    /**
     * PartialPullInfo
     * @description A named gap in the evidence (D24/F4-S6) — "2025 inactive missing".
     */
    PartialPullInfo: {
      /** Missing */
      missing: string[];
      /** Calls To Complete */
      calls_to_complete: number;
    };
    /**
     * Subject
     * @description The unit being priced. Not a comp: it is never evidence for itself.
     */
    Subject: {
      /** Address */
      address: string;
      /** Lat */
      lat: number;
      /** Lng */
      lng: number;
      /** Sqft */
      sqft: number;
      /** Beds */
      beds: number;
      /** Baths */
      baths: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Derive the full state
   * @description Derive everything from one complete curation state.
   *
   * 404 when the pull is gone — a stale workspace pointing at a deleted pull
   * is a normal condition, not a server error. 422 (from the request model)
   * for an unknown field, a `selections` key, or a negative weight: each of
   * those is curation that would otherwise fail silently.
   */
  post_derive_api_derive_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["DeriveRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DerivedState"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
